name: Cargo Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Đổi từ ubuntu-latest sang windows-latest để build file .exe cho Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Build Release
      run: cargo build --release

    # Xuất file chạy .exe ra ngoài giao diện GitHub Actions
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: peaTagger-windows
        path: target/release/peaTagger.exe
